### ISSUE TITLE
How to generate correct PSFs?

### ISSUE THREAD

**Issue by MeLonJ10** [Image-Science-Lab-cmu/UPC_ICCP21_Code#1]
Hi Anqi, thanks for the wonderful work. 
I am trying to reproduce the blur PSFs in Figure 5 of the original paper. However, I got some different results. 
![repeat_TOLED](https://user-images.githubusercontent.com/41948801/145329843-9feac9c0-945c-40e2-ae91-9044b60da033.png)
![random_TOLED](https://user-images.githubusercontent.com/41948801/145329855-2164d49d-dfee-4d10-ac17-8644c106f046.png)
These two PSFs are generated with T-OLED/periodic tiling and T-OLED/random tiling, respectively.
There are some modifications based on your official code:
1. the variable  "u1" of computePSF_3.m is generated with the function "rect" instead of "circ", since the latter is not provided;
2. the "phaseOpt" is set to an empty string, since the variable "h1" is not provided.
It would be greatly appreciated if you could provide some help to solve this problem.

**Comment by AnqiYang** [comment]
Hi Xihao,

Thank you for your interest in our work! We really appreciate your troubleshooting.

I updated the Github repo with the missing file and cleared up deprecated variables. Please work with the current version. 
To reproduce Figure 5 using simulate.m, please replace #Line 70,71 with the following code:

[PSFs, openRatio] = computePSF_3smooth(srcPath, dstDir, ...
    tileOptions{id}, thresholds(id), unitPatternSize, delta1);

Note that,
computePSF_3smooth --- computes PSF for multiple wavelengths;
computePSF_3 --- computes PSF for three peak wavelengths.

Please let me know if you still have trouble reproducing the result.

**Comment by MeLonJ10** [comment]
Hi Anqi,
Thank you for the reply. I could reproduce the correct PSFs.
